//! Shared app icon data (embedded at compile time from assets/icon.png).
//!
//! `W`/`H` are generated by build.rs from the PNG header, so re-rendering
//! assets/icon.png at a different resolution needs no source change.
pub const RGBA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/icon_rgba.bin"));
include!(concat!(env!("OUT_DIR"), "/icon_dims.rs"));
